# Site settings
title: overtrue
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# permalink: /articles/:categories/:title/
# baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site

domain:    overtrue.me
paginate:   10

# Build settings
markdown: kramdown

disqus:
  id: overtrueme

google:
    analytics_id: UA-55452630-1