title: Kaiyuan's Blog
name: Kaiyuan Liu
description: Kaiyuan Liu, Driven, dynamic and highly qualified sofware engineer with a broad range of experience in technical software development. Experienced in a variety of platforms, languages and embedded systems
keywords: Java, Spring, Hibernate, JBoss/Wildfly, PHP, Laravel
skill_keywords: [Java, Spring, Hibernate, PHP, HTML+CSS, JavaScript, Linux, Laravel, Git, Mac, RESTful, Stackoverflow]

timezone: UTC
encoding: "utf-8"

url: http://kaiyuanliu.me
baseurl:  "/"
domain:    kaiyuanliu.me
permalink:     /:categories/:year/:month/:title.html
paginate_path: 'page:num'
paginate:   10
source_code: https://github.com/kaiyuanliu/kaiyuanliu.github.io
copy_right: 2016

# Build settings
markdown:    kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      category: "articles"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

kramdown:
  input: GFM
  syntax_highlighter: rouge

gems:
  - jemoji
  - rouge
  - jekyll-html-pipeline
  - jekyll-paginate

disqus:
  shortname: kaiyuanliu

analytics:
  provider: google
  google:
    analytics_id: UA-76104500-1

github:
  user_name: kaiyuanliu


# navigation
navs:
  -
    href: /
    label: Home

  -
    href: /open-source
    label: Open-Source

  -
    href: https://github.com/Kaiyuanliu
    label: GitHub
    target: _blank

  -
    href: /about
    label: About