title: overtrue - 安正超博客
name: overtrue
email: anzhengchao@gmail.com
description: 安正超，网名overtrue，PHP工程师，从事web相关的开发工作。开源爱好者，GitHub:https://github.com/overtrue。
keywords: Laravel,Laravel教程,Laravel安装,Laravel视频,安正超,overtrue,Pinyin,汉字转拼音
skill_keywords: [PHP, Javascript, HTML+CSS, Linux, Laravel, Git, Mac, RESTful, Stackoverflow, Sublime Text, OmniGaffale, OminiPlan]

timezone:    PRC
encoding: "utf-8"

url: http://overtrue.me
baseurl:  "/"
domain:    overtrue.me
permalink:     /articles/:year/:month/:title.html
paginate_path: 'page:num'
paginate:   10
source_code: https://github.com/overtrue/overtrue.github.io

# Build settings
markdown:    kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

quiet:    false
defaults: []

rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

  coderay:
    coderay_wrap:              div
    coderay_line_numbers:      inline
    coderay_line_number_start: 1
    coderay_tab_width:         4
    coderay_bold_every:        10
    coderay_css:               style

gems:
  # - jemoji
  # # - rouge
  # # # - jekyll-mentions
  # - jekyll-sitemap
  # - jekyll-html-pipeline

disqus:
  id: overtrueme

google:
    analytics_id: UA-55452630-1

# navigation
navs:
  -
    href: /
    label: Home

  -
    href: /open-source.html
    label: Open-Source

  -
    href: https://github.com/overtrue
    label: GitHub
    target: _blank

  -
    href: http://weibo.com/44294631
    label: Weibo
    target: _blank

  -
    href: /about
    label: About

popular_repos: ['pinyin', 'wechat', 'writor', 'laravel-wechat', 'laravel-lang', 'laravel-pinyin', 'latest-laravel', 'latest-lumen']
contribute_repos: ['laravel/framework', 'tymondesigns/jwt-auth', 'caouecs/Laravel-lang']