# Site settings
title: overtrue - 安正超博客
name: overtrue
email: anzhengchao@gmail.com
description: 安正超，网名overtrue，PHP工程师，从事web相关的开发工作。开源爱好者，GitHub:https://github.com/overtrue。
keywords: Laravel,Laravel教程,Laravel安装,Laravel视频,安正超,overtrue,Pinyin,汉字转拼音

# permalink: /articles/:categories/:title/
# baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
url: http://overtrue.me
baseurl:  "/"
domain:    overtrue.me
permalink:     /articles/:categories/:title/
paginate_path: 'page:num'
paginate:   10


# Build settings
future:      true
# markdown: kramdown
markdown: HTMLPipeline
highlighter: pygments
# kramdown:
#   input: GFM
#   auto_ids: true
#   footnote_nr: 1
#   entity_output: as_char
#   toc_levels: 1..6
#   smart_quotes: lsquo,rsquo,ldquo,rdquo
#   use_coderay: true
# coderay:
#   coderay_wrap: div
#   coderay_line_numbers: nil
#   coderay_tab_width: 4
#   coderay_bold_every: 10
#   coderay_css: class
# excerpt_separator: "\n\n"

markdown: HTMLPipeline
html_pipeline:
  filters:
    - "markdownfilter"
    - "sanitizationfilter"
    - "emojifilter"
    - "mentionfilter"

gems:
  - jemoji
  # - jekyll-mentions
  - jekyll-sitemap
  - jekyll-html-pipeline

disqus:
  id: overtrueme

google:
    analytics_id: UA-55452630-1

timezone:    PRC
encoding:    UTF-8

# navigation
navs:
  -
    href: /
    label: Home

  -
    href: /open-source.html
    label: Open-Source

  -
    href: https://github.com/overtrue
    label: GitHub
    target: _blank

  -
    href: http://weibo.com/44294631
    label: Weibo
    target: _blank

  -
    href: /about
    label: About

popular_repos: ['pinyin', 'wechat', 'writor', 'laravel-wechat', 'laravel-lang', 'laravel-pinyin', 'latest-laravel', 'latest-lumen']
contribute_repos: ['laravel/framework', 'tymondesigns/jwt-auth', 'caouecs/Laravel-lang']