# Site settings
title: overtrue - 安正超博客
name: overtrue
email: anzhengchao@gmail.com
description: 安正超，网名overtrue，PHP工程师，从事web相关的开发工作。开源爱好者，GitHub:https://github.com/overtrue。
keywords: Laravel,Laravel教程,Laravel安装,Laravel视频,安正超,overtrue,Pinyin,汉字转拼音

# permalink: /articles/:categories/:title/
# baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
url: http://overtrue.me
baseurl:  "/"
domain:    overtrue.me
permalink:     /articles/:categories/:title/
paginate_path: 'page:num'
paginate:   10

# Build settings
markdown: kramdown
highlighter: pygments

gems:
  - jemoji
  - jekyll-mentions
  - jekyll-sitemap

disqus:
  id: overtrueme

google:
    analytics_id: UA-55452630-1

timezone:    PRC
encoding:    UTF-8

# navigation
navs:
  -
    href: /
    label: Home

  -
    href: /open-source.html
    label: Open-Source

  -
    href: https://github.com/overtrue
    label: GitHub
    target: _blank

  -
    href: http://weibo.com/44294631
    label: Weibo
    target: _blank

  -
    href: /about
    label: About
