source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
include:     ['.htaccess']
exclude:     []
keep_files:  ['.git','.svn']
timezone:    PRC
encoding:    UTF-8

future:      true
show_drafts: nil
limit_posts: 0
pygments:    true

relative_permalinks: true

permalink:     date
paginate_path: 'page:num'

markdown:      kramdown
#markdown: redcarpet
#redcarpet:
 # extensions: [fenced_code_blocks]
markdown_ext:  markdown,md
textile_ext:   textile
kramdown:
  input: GFM

excerpt_separator: "\n\n"